### ISSUE TITLE
FEATURE: sidebar

### ISSUE THREAD

**Issue by bianbbc87** [PEER-Re/PEERRE-FRONT#12]
## 🔨 Description

- sidebar 클릭 시 활성화 스타일 완성

## ✅ Tasks

- [ ] 각각의 버튼 클릭 시 경로 수정
- [ ] 버튼 클릭시 이미지, 폰트 색상 변경 사항 수정
- [ ] styled props dom warning 픽스
